---
abstract: "Perl module for accessing Sailthru's API"
author:
  - 'Sam Gerstenzang <sgerstenzang@stanford.edu>, Steve Miketa <steve@sailthru.com>, Steve Sanbeg <stevesanbeg@buzzfeed.com>, Finn Smith <finn@timeghost.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sailthru-Client
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: 0
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Params::Validate: 0
  Readonly: 0
  Test::Exception: 0
  Test::MockModule: 0
  URI: 0
version: 2.002
